// Rendering the finished note.
//
// Markdown, because the output is meant to be kept: it drops into Obsidian,
// a repo, or any notes app, and it still reads fine as plain text in a terminal.
import { basename } from 'node:path'
import { formatTimestamp } from './segments.js'

/**
 * Render one line of a list, with its timestamp when we found one.
 *
 * Lines that could not be located are still shown. Dropping them would quietly
 * lose real content because the matcher was unsure, which is the wrong trade:
 * a missing timestamp is a small gap, a missing action item is a bug.
 */
function renderItem ({ text, startMs }) {
  return startMs === null ? `- ${text}` : `- ${text} _(${formatTimestamp(startMs)})_`
}

function renderSection (heading, items, emptyNote) {
  if (items.length === 0) return `## ${heading}\n\n_${emptyNote}_`

  return `## ${heading}\n\n${items.map(renderItem).join('\n')}`
}

/**
 * Build the Markdown note.
 *
 * @param {object} params
 * @param {string} params.sourcePath   Audio file the note came from.
 * @param {string} params.summary
 * @param {Array<{text: string, startMs: number|null}>} params.actions
 * @param {Array<{text: string, startMs: number|null}>} params.decisions
 * @param {Array<{text: string, startMs: number, endMs: number}>} params.utterances
 * @param {object} params.meta        { asrModel, llmModel, durationMs, elapsedMs }
 * @returns {string}
 */
export function renderNote ({ sourcePath, summary, actions, decisions, utterances, meta }) {
  const file = basename(sourcePath)
  const transcript = utterances
    .map((u) => `**${formatTimestamp(u.startMs)}** ${u.text}`)
    .join('\n\n')

  const duration = meta.durationMs ? formatTimestamp(meta.durationMs) : 'unknown'
  const seconds = (meta.elapsedMs / 1000).toFixed(1)

  return [
    `# ${file}`,
    '',
    `_${duration} of audio, processed on-device in ${seconds}s._`,
    '',
    '## Summary',
    '',
    summary || '_The model returned nothing for this recording._',
    '',
    renderSection('Action items', actions, 'None found.'),
    '',
    renderSection('Decisions', decisions, 'None found.'),
    '',
    '## Transcript',
    '',
    transcript,
    '',
    '---',
    '',
    `Generated by [echoscribe](https://github.com/adibbabrar/echoscribe) with the QVAC SDK. ` +
    `Transcribed with \`${meta.asrModel}\`, written up with \`${meta.llmModel}\`. ` +
    'Everything ran locally; no audio or text left this machine.',
    ''
  ].join('\n')
}
